name: CI

on:
  push:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.5

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build code
        run: pnpm build

      - name: Run tests
        run: pnpm test
